name: gbif_download_standalone
channels:
  - defaults
  - pytorch
  - anaconda
dependencies:
  - python
  - matplotlib
  - numpy
  - pip
  - pandas
  - pre_commit
  - isort
  - flake8
  - pip:
    - pygbif
    - python-dwca-reader
